Repository gravity-ui/uikit, pull requests merged in 2023-06, with the labels that each got.

#655 feat: add new component Pagination
  CODEOWNERS
  package-lock.json
  package.json
  src/components/Pagination/Pagination.scss
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/README.md
  src/components/Pagination/__stories__/Pagination.stories.tsx
  src/components/Pagination/components/PaginationButton/PaginationButton.tsx
  src/components/Pagination/components/PaginationEllipsis/PaginationEllipsis.scss
  src/components/Pagination/components/PaginationEllipsis/PaginationEllipsis.tsx
  src/components/Pagination/components/PaginationInput/PaginationInput.scss
  src/components/Pagination/components/PaginationInput/PaginationInput.tsx
  src/components/Pagination/components/PaginationPage/PaginationPage.scss
  src/components/Pagination/components/PaginationPage/PaginationPage.tsx
  src/components/Pagination/components/PaginationPageOf/PaginationPageOf.scss
  src/components/Pagination/components/PaginationPageOf/PaginationPageOf.tsx
  src/components/Pagination/components/PaginationPageSizer/PaginationPageSizer.tsx
  src/components/Pagination/components/index.ts
  src/components/Pagination/hooks/usePagination.ts
  src/components/Pagination/i18n/en.json
  src/components/Pagination/i18n/index.ts
  src/components/Pagination/i18n/ru.json
  src/components/Pagination/index.ts
  src/components/Pagination/types.ts
  src/components/Pagination/utils.test.ts
  src/components/Pagination/utils.ts
  src/components/index.ts
Labels: feat

#744 feat!: remove `resize-observer-polyfill`
  package-lock.json
  package.json
  src/components/Breadcrumbs/Breadcrumbs.tsx
  src/components/Table/Table.tsx
  src/components/utils/useElementSize.ts
  test-utils/setup-tests.ts
Labels: breaking change

#703 feat(Menu): change extra pseudo classes in markup to padding's
  src/components/Menu/Menu.scss
Labels: component: Menu

#668 feat(Select): add hasClear property
  src/components/Select/README.md
  src/components/Select/Select.tsx
  src/components/Select/__stories__/Select.stories.tsx
  src/components/Select/__stories__/SelectShowcase.scss
  src/components/Select/__stories__/SelectShowcase.tsx
  src/components/Select/__stories__/constants.ts
  src/components/Select/__tests__/Select.base-actions.test.tsx
  src/components/Select/__tests__/Select.clear.test.tsx
  src/components/Select/__tests__/Select.muitiple.test.tsx
  src/components/Select/__tests__/Select.single.test.tsx
  src/components/Select/__tests__/utils.tsx
  src/components/Select/components/SelectClear/SelectClear.scss
  src/components/Select/components/SelectClear/SelectClear.tsx
  src/components/Select/components/SelectControl/SelectControl.scss
  src/components/Select/components/SelectControl/SelectControl.tsx
  src/components/Select/constants.ts
  src/components/Select/i18n/en.json
  src/components/Select/i18n/index.ts
  src/components/Select/i18n/ru.json
  src/components/Select/types.ts
  src/components/utils/useSelect/useSelect.ts
Labels: component: Select

#711 refactor!: remove popup wrapper class, use content classes for popover…
  src/components/Popover/Popover.scss
  src/components/Popover/Popover.tsx
  src/components/Popover/README.md
  src/components/Popover/__stories__/Popover.stories.tsx
  src/components/Popover/types.ts
  src/components/Popup/Popup.scss
  src/components/Popup/Popup.tsx
  src/components/SharePopover/README.md
  src/components/SharePopover/SharePopover.scss
  src/components/SharePopover/SharePopover.tsx
  src/components/Tooltip/Tooltip.scss
Labels: breaking change
