Repository gravity-ui/uikit, pull requests merged in 2023-12, with the labels that each got.

#831 feat(Table): use `<colgroup/>` to set cells width
  src/components/Table/Table.tsx
Labels: component: Table

#1121 feat: add new layout component `Box`
  src/components/Alert/__snapshots__/Alert.test.tsx.snap
  src/components/Card/Card.tsx
  src/components/layout/Box/Box.scss
  src/components/layout/Box/Box.tsx
  src/components/layout/Col/__stories__/Col.stories.tsx
  src/components/layout/Container/__stories__/Container.stories.tsx
  src/components/layout/Flex/Flex.scss
  src/components/layout/Flex/Flex.tsx
  src/components/layout/Flex/__stories__/Flex.stories.tsx
  src/components/layout/LayoutProvider/__stories__/Layout.mdx
  src/components/layout/LayoutProvider/__stories__/Layout.stories.tsx
  src/components/layout/Row/__stories__/Row.stories.tsx
  src/components/layout/index.ts
  src/components/layout/variables.scss
Labels: feat

#1198 feat(Toaster)!: use theme prop instead of type
  src/components/Toaster/README.md
  src/components/Toaster/Toast/Toast.scss
  src/components/Toaster/Toast/Toast.tsx
  src/components/Toaster/__stories__/ToasterShowcase.scss
  src/components/Toaster/__stories__/ToasterShowcase.tsx
  src/components/Toaster/types.ts
Labels: breaking change
