Repository gravity-ui/uikit, pull requests merged in 2024-03, with the labels that each got.

#1390 fix(Slider): add export for Slider
  src/components/index.ts
Labels: component: Slider

#1388 feat(Popup): add transition callbacks
  src/components/Popup/Popup.tsx
  src/components/Popup/README.md
Labels: component: Popup

#1410 chore(Slider): add codeowner
  CODEOWNERS
Labels: infra, component: Slider

#1416 chore: fix gulp clean task
  gulpfile.js
Labels: infra

#1318 feat: improve focus outline styles for text/select inputs
  src/components/Select/README.md
  src/components/Select/components/SelectControl/SelectControl.scss
  src/components/controls/TextArea/README.md
  src/components/controls/TextArea/TextArea.scss
  src/components/controls/TextInput/README.md
  src/components/controls/TextInput/TextInput.scss
Labels: a11y
